### ISSUE TITLE
Verwendungszweck Berechnung falsch?

### ISSUE THREAD

**Issue by JohannMaierhofer** [willuhn/obantoo#3]
Kann es sein, dass die Zeile 306 in Zahler.java nicht funktioniert?
verwendungszweck += " " + this.getBetrag();

Jedenfalls wird in JVerein beim add zwar der zweite Zahler angehängt und auch mit Betrag aber vorher wird der Betrag des ersten Zahlers nicht angehängt. Das hätte eigentlich in der Zeile 306 passieren sollen.

**Comment by willuhn** [comment]
@lenilsas Kannst du dir das bitte mal anschauen? Das hattest du eingebaut: https://github.com/willuhn/obantoo/commit/a24ba4ac6ed6d8fa8faa2c8b2f91373a8203ac1f

**Comment by JohannMaierhofer** [comment]
Das war vorher Zeile 308 und auch schon so.

**Comment by JohannMaierhofer** [comment]
Wahrscheinlich geht es mit
verwendungszweck =  verwendungszweck + " " + this.getBetrag();
Ich glaube ich hatte schon mal ein ähnliches Problem mit dem +=.

**Comment by lenilsas** [comment]
@JohannMaierhofer hast du die aktuelle Version von Obantoo verwendet die im Nigthly Build von Hibiscus enthalten ist?

**Comment by JohannMaierhofer** [comment]
Nein, ich teste hier Jverein in Eclipse und habe den 2.10 Branch von Hibiscus.

**Comment by JohannMaierhofer** [comment]
Ich kann heute Abend mal nachschauen ob ich den letzten Git Stand von Hibiscus habe. Da müsste doch dann die neueste Version dabei sein.

**Comment by JohannMaierhofer** [comment]
Ich habe es jetzt nochmals ausprobiert.
Die obantoo version aus dem Hisbiscus 2_10_Branch ist die hier:
![Bildschirmfoto_20240827_183113](https://github.com/user-attachments/assets/9f5a2a3b-217c-4f3a-aa03-d7f4979d9774)

Bei einem Abrechnungslauf mit Lastschrift und Beitrag mit sekundären Beitragsgruppe entsteht das:
![Bildschirmfoto_20240827_183718](https://github.com/user-attachments/assets/8b592144-cc22-4ce4-82c3-406da53ffe34)

Bei der ersten Buchung nur mit sekundären Beitragsgruppen (Individueller Beitrag = 0€) fehlt bei SEKUNDAER der Betrag 10€.
Die 300€ beim Beitrag fehlen bei der zweiten Buchung.
Also fehlt immer beim der ersten Buchung der Betrag. Eigentlich müsste der Code die Stelle durchlaufen wo der Betrag angehängt wird. Zumindest lese ich den Code so, dass es passieren sollte.
Wie ich oben geschrieben habe könnte es evtl. an dem += liegen. Da hatte ich auch schon einmal das Problem, dass es damit nicht ging und erst mit der Umstellung auf = ging es.

**Comment by lenilsas** [comment]
Merkwürdig, bei mir funktioniert es einwandfrei, ich habe gerade nochmal komplett neu installiert mit dem Nigthly und es ging. Welches Betriebssystem hast du? Ich verwende Ubuntu.
Kannst du mal durch den Code Debuggen, da müsstest du ja sehen können, ob an der Stelle der Code richtig ausgeführt wird.

**Comment by willuhn** [comment]
@JohannMaierhofer Bitte verwende mal entweder das Nightly-Build von Hibiscus oder den master-Branch, falls du Hibiscus aus GIT verwendest. Nur dort ist die aktuelle obantoo-Version mit den letzten Änderungen enthalten.

Ich plane aber in den nächsten Tagen ein neues Hibiscus-Release. Gebt bitte Bescheid, falls an Obantoo noch Änderungen nötig sind, damit diese noch eingebaut werden können, bevor das Hibiscus-Release live geht.

**Comment by JohannMaierhofer** [comment]
Ich habe mir jetzt die obantoo Lib aus dem Main Branch kopiert. Damit geht es.
Entschuldigung für die Aufregung. Da hat wohl jemand den Bug früher gefunden.

**Comment by willuhn** [comment]
OK, dann würde ich das Ticket hier schließen.
